---
# tasks file for docker_install

- name: install docker
  apt: 
     name: "{{ item  }}"
     state: present
     update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  

      #- name: install docker repo from docker website
      #  get_url:
      #    url: "https://download.docker.com/linux/ubuntu/gpg#"
      #    dest: "/usr/share/keyrings/docker-archive-keyring.gpg"
      #    mode: '0644'
      

      #- name: install docker gpg 
      #  command: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
- name: Download Docker GPG key
  get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "/tmp/docker-gpg"
    mode: '0644'

- name: Convert GPG key to binary format
  shell: "gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg < /tmp/docker-gpg"
  args:
    creates: "/usr/share/keyrings/docker-archive-keyring.gpg"


      #- name: Add docker repo 
      #  apt_repository: 
      #    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }}  stable"
      #    repo: "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
      #    state: present
      #    filename: docker     

- name: add docker repo
  command: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'



      # kda a7na 3mlna gbna gpg key and installed docker repo + match the gpg key with repo  
      # now we need to install all tools we need to install docker

- name: Update APT
  apt:
    update_cache: yes

- name: install docker tools
  apt: 
     name: 
       - docker-ce
       - docker-ce-cli 
       - containerd.io
     state: present
     update_cache: yes    
     
- name: Ensure Docker service is running
  service:
        name: docker
        state: started
        enabled: yes


      #- name: start & enable docker
      #  service:
      #    name: #docker
      #    state: started
      #    enabled: yes
